### ISSUE TITLE
[feature]: Add more social channels to README and Registration Form

### ISSUE THREAD

**Issue by nehagup** [keploy/student-program#5]
### Is there an existing feature request for this?

- [x] I have searched the existing issues

### Summary

Since this website is particularly for student programs, it should contain the all social channels of Keploy where the engagement can happen and the registration link to the program.

### Why should this be worked on?

Adds more navigation and community support.

**Comment by mukul314** [comment]
@nehagup what should I write next to the links....
like - Get connected on linkedin??

**Comment by nehagup** [comment]
@mukul314 this issue is stale now.
