### ISSUE TITLE
[bug]: Make all buttons consistent

### ISSUE THREAD

**Issue by nehagup** [keploy/student-program#6]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The "Star us on Github" button does not have uniform spacing/padding around and inside it. 

All the buttons in the website should have consistency and hover effects. 

### Steps to reproduce

<img width="236" alt="Screenshot 2022-05-06 at 10 36 48 PM" src="https://user-images.githubusercontent.com/15074229/167179445-5b1219d0-7592-483a-9d3c-708d8748035d.png">

### Version

Cloud

**Comment by daniel-moderiano** [comment]
Happy to work on this issue as well - what kind of hover effects would you like to see on the buttons?

**Comment by nehagup** [comment]
@daniel-moderiano please feel free to resolve this. We're expecting to have normal bg-color change on hover. :)
