### ISSUE TITLE
[feature]: Add Keploy (orange) theme to the website

### ISSUE THREAD

**Issue by nehagup** [keploy/student-program#7]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Change all vectors and H1 colours to Keploy Orange colour. 

### Why should this be worked on?

Will add consistency and authenticity to the website.

**Comment by littleironical** [comment]
Hi Neha, you can assign this task to me

**Comment by littleironical** [comment]
I've created a pull request #9

**Comment by littleironical** [comment]
@nehagup you can close this issue now, this feature has been implemented and added to the main code.

**Comment by nehagup** [comment]
Thanks @littleironical :)
